# Generated by Django 3.0.6 on 2020-05-25 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redactor', '0003_auto_20200525_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='title',
        ),
    ]
